language: php

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.xml
